import { mkdir, readFile, rm, writeFile, access } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { childSummaryPath } from './config.js';
import { extractFilePaths } from './summary-parser.js';
import type { ChildSession, TreeConfig } from '../types/index.js';

export interface ExportObsidianOptions {
  tree?: TreeConfig;
}

export interface ExportObsidianResult {
  vaultPath: string;
  cctreeDir: string;
  treesWritten: number;
  childrenWritten: number;
}

const MONTHS = [
  'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
];

function shortDate(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return '';
  return `${MONTHS[d.getMonth()]} ${d.getDate()}`;
}

function isoDay(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const dd = String(d.getDate()).padStart(2, '0');
  return `${yyyy}-${mm}-${dd}`;
}

function statusIcon(status: ChildSession['status']): string {
  switch (status) {
    case 'committed': return '✓';
    case 'active': return '⚡';
    case 'abandoned': return '✗';
  }
}

function countsFor(tree: TreeConfig): { committed: number; active: number; abandoned: number } {
  const counts = { committed: 0, active: 0, abandoned: 0 };
  for (const c of tree.children) counts[c.status] += 1;
  return counts;
}

function countsLine(tree: TreeConfig): string {
  const c = countsFor(tree);
  const parts: string[] = [];
  if (c.committed) parts.push(`${c.committed} committed`);
  if (c.active) parts.push(`${c.active} active`);
  if (c.abandoned) parts.push(`${c.abandoned} abandoned`);
  return parts.length ? parts.join(', ') : 'no sessions yet';
}

function yamlString(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

export function renderIndex(trees: TreeConfig[]): string {
  const lines: string[] = [];
  lines.push('---');
  lines.push('tags: [cctree]');
  lines.push('---');
  lines.push('');
  lines.push('# cctree — Session Trees');
  lines.push('');
  lines.push('> Generated by `cctree export obsidian` — re-running overwrites this folder.');
  lines.push('');

  if (trees.length === 0) {
    lines.push('No trees yet. Run `cctree init` to create one.');
    lines.push('');
    return lines.join('\n');
  }

  for (const tree of trees) {
    lines.push(`- [[${tree.slug}/_index|${tree.name}]] — ${countsLine(tree)}`);
  }

  const totalSessions = trees.reduce((acc, t) => acc + t.children.length, 0);
  lines.push('');
  lines.push(`Total: ${trees.length} tree${trees.length === 1 ? '' : 's'}, ${totalSessions} session${totalSessions === 1 ? '' : 's'}.`);
  lines.push('');

  return lines.join('\n');
}

export function renderTreeIndex(
  tree: TreeConfig,
  missingSummarySlugs: Set<string> = new Set(),
): string {
  const lines: string[] = [];
  lines.push('---');
  lines.push(`tree: ${tree.slug}`);
  lines.push(`tags: [cctree, ${yamlString(`cctree/tree/${tree.slug}`)}]`);
  lines.push('---');
  lines.push('');
  lines.push(`# ${tree.name}`);
  lines.push('');
  lines.push(`**Slug**: \`${tree.slug}\``);
  lines.push(`**Created**: ${isoDay(tree.created_at)}`);
  lines.push(`**Sessions**: ${countsLine(tree)}`);
  lines.push('');
  lines.push('## Children');
  lines.push('');

  if (tree.children.length === 0) {
    lines.push('_No sessions yet._');
    lines.push('');
    return lines.join('\n');
  }

  for (const child of tree.children) {
    const icon = statusIcon(child.status);
    if (child.status === 'committed') {
      const dateStr = child.committed_at ? ` ${shortDate(child.committed_at)}` : '';
      if (missingSummarySlugs.has(child.slug)) {
        lines.push(`- ${child.name} · ${icon} committed${dateStr} (missing summary)`);
      } else {
        lines.push(`- [[${child.slug}]] · ${icon} committed${dateStr}`);
      }
    } else if (child.status === 'active') {
      lines.push(`- ${child.name} · ${icon} active (no summary yet)`);
    } else {
      lines.push(`- ${child.name} · ${icon} abandoned`);
    }
  }
  lines.push('');

  return lines.join('\n');
}

export function renderChild(
  tree: TreeConfig,
  child: ChildSession,
  summary: string,
): string {
  const lines: string[] = [];

  // Frontmatter
  lines.push('---');
  lines.push(`tree: ${tree.slug}`);
  lines.push(`tree-name: ${yamlString(tree.name)}`);
  lines.push(`status: ${child.status}`);
  lines.push(`created: ${child.created_at}`);
  if (child.committed_at) lines.push(`committed: ${child.committed_at}`);
  const tagList = [
    'cctree',
    yamlString(`cctree/tree/${tree.slug}`),
    yamlString(`cctree/status/${child.status}`),
  ].join(', ');
  lines.push(`tags: [${tagList}]`);
  if (child.worktree?.branch) {
    lines.push(`worktree-branch: ${yamlString(child.worktree.branch)}`);
  }
  lines.push('---');
  lines.push('');

  // Title
  lines.push(`# ${child.name}`);
  lines.push('');

  // Navigation
  lines.push(`Parte de [[_index|${tree.name}]].`);
  const siblings = tree.children.filter(
    (c) => c.slug !== child.slug && c.status === 'committed',
  );
  if (siblings.length > 0) {
    const links = siblings.map((s) => `[[${s.slug}]]`).join(', ');
    lines.push(`Irmãs committed: ${links}`);
  }
  lines.push('');

  // Summary content verbatim
  lines.push(summary.trim());
  lines.push('');

  // Related files (extractor)
  const paths = extractFilePaths(summary);
  if (paths.length > 0) {
    lines.push('## Related files');
    lines.push('');
    for (const path of paths) {
      lines.push(`- [[file:${path}]]`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

async function loadSummary(tree: TreeConfig, child: ChildSession): Promise<string | null> {
  const summaryPath = childSummaryPath(tree.slug, child.slug);
  try {
    return await readFile(summaryPath, 'utf-8');
  } catch {
    return null;
  }
}

export async function exportToObsidian(
  vaultPath: string,
  allTrees: TreeConfig[],
  options: ExportObsidianOptions = {},
): Promise<ExportObsidianResult> {
  const vault = resolve(vaultPath);

  if (!(await fileExists(vault))) {
    throw new Error(
      `Vault path "${vault}" does not exist. Create the directory (or open a vault in Obsidian) before running this command.`,
    );
  }

  const targetTrees = options.tree ? [options.tree] : allTrees;
  const cctreeDir = join(vault, 'cctree');

  if (options.tree) {
    // When exporting a single tree, only wipe and regenerate THAT tree's
    // subfolder so the rest of the vault (including other cctree/<slug>
    // subfolders) stays intact. Do not touch index.md either.
    const treeDir = join(cctreeDir, options.tree.slug);
    await rm(treeDir, { recursive: true, force: true });
    await mkdir(treeDir, { recursive: true });
  } else {
    // Full export: nuke the entire cctree/ subfolder and regenerate.
    await rm(cctreeDir, { recursive: true, force: true });
    await mkdir(cctreeDir, { recursive: true });
  }

  let childrenWritten = 0;

  for (const tree of targetTrees) {
    const treeDir = join(cctreeDir, tree.slug);
    await mkdir(treeDir, { recursive: true });

    // Resolve committed children's summaries up front so the tree _index.md
    // can mark children whose summary file is missing on disk.
    const loadedSummaries = new Map<string, string>();
    const missingSummarySlugs = new Set<string>();
    for (const child of tree.children) {
      if (child.status !== 'committed') continue;
      const summary = await loadSummary(tree, child);
      if (summary === null) missingSummarySlugs.add(child.slug);
      else loadedSummaries.set(child.slug, summary);
    }

    await writeFile(join(treeDir, '_index.md'), renderTreeIndex(tree, missingSummarySlugs));

    for (const child of tree.children) {
      const summary = loadedSummaries.get(child.slug);
      if (!summary) continue;
      await writeFile(
        join(treeDir, `${child.slug}.md`),
        renderChild(tree, child, summary),
      );
      childrenWritten += 1;
    }
  }

  if (!options.tree) {
    await writeFile(join(cctreeDir, 'index.md'), renderIndex(allTrees));
  }

  return {
    vaultPath: vault,
    cctreeDir,
    treesWritten: targetTrees.length,
    childrenWritten,
  };
}
